### ISSUE TITLE
Enable users to opt-out of PSICAT google-analytics launch-tracker 

### ISSUE THREAD

**Issue by knbknb** [laccore/coretools#5]
##### Enhancement request

I use PSICAT under wine.

There is a couple of lines of code in file
`tools/PSICAT/griffon-app/lifecycle/Ready.groovy` that contains a Google Analytics tracker that causes some trouble for me. It's just a warning not an error, so immediaqte action is not really required here.

I assume the Google Analytics Tracker for LacCore still works, collecting valueable high-level usage-statistics, e.g. how many times PSICAT has started up, on which platforms, in which countries, etc.

Nothing wrong with that, but is so happens that I for one have blocked Google Analytics SSL Endpoints. I have blocked them on operating-system level, by aliasing the Google servers to 0.0.0.0 .  (See https://github.com/StevenBlack/hosts/ repo.) There was something else I did  to really block them, I don't remember.

So when PSICAT starts there are always huge JVM stacktraces in the terminal window due to failed SSL connection requests.

I think  there should be a way for users to opt-out of Google Analytics. Perhaps a simple config file, or an `.env` file with some magic parameters.

**Comment by knbknb** [comment]
Stack trace 

```
INFO (GoogleAnalytics.java:99) - Initializing Google Analytics with config=GoogleAnalyticsConfig [threadNameFormat=googleanalytics-thread-{0}, enabled=true, maxThreads=1, useHttps=true, validate=true, httpUrl=http://www.google-analytics.com/collect, httpsUrl=https://ssl.google-analytics.com/collect, userAgent=java/1.8.0_171-b11/Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/Windows Server 2008 R2/6.1/amd64, proxyPort=80, deriveSystemParameters=true, gatherStats=false] and defaultRequest=Request [parms={HIT_TYPE=pageview, USER_LANGUAGE=en-US, PROTOCOL_VERSION=1, CLIENT_ID=d543bf19-f0e3-43f7-9be5-6ef8623793a8, TRACKING_ID=UA-64269312-1, DOCUMENT_ENCODING=Cp1252}, customDimensions={}, customMetrics={}]
DEBUG (GoogleAnalytics.java:137) - Processing Request [parms={HIT_TYPE=pageview, PROTOCOL_VERSION=1, DOCUMENT_URL=http://www.laccore.org, DOCUMENT_TITLE=launch: UUID=2a165524-60f1-4c86-aa16-ff5e487c0a91}, customDimensions={}, customMetrics={}]
DEBUG (GoogleAnalytics.java:148) - Processed all parameters and sending the request [t=pageview, ul=en-US, v=1, cid=d543bf19-f0e3-43f7-9be5-6ef8623793a8, dl=http://www.laccore.org, tid=UA-64269312-1, de=Cp1252, dt=launch: UUID=2a165524-60f1-4c86-aa16-ff5e487c0a91]
DEBUG (RequestAddCookies.java:122) - CookieSpec selected: best-match
DEBUG (RequestAuthCache.java:75) - Auth cache not set in the context
DEBUG (PoolingHttpClientConnectionManager.java:215) - Connection request: [route: {s}->https://ssl.google-analytics.com:443][total kept alive: 0; route allocated: 0 of 1; total allocated: 0 of 20]
DEBUG (PoolingHttpClientConnectionManager.java:246) - Connection leased: [id: 0][route: {s}->https://ssl.google-analytics.com:443][total kept alive: 0; route allocated: 1 of 1; total allocated: 1 of 20]
DEBUG (MainClientExec.java:216) - Opening connection {s}->https://ssl.google-analytics.com:443
DEBUG (HttpClientConnectionOperator.java:114) - Connecting to ssl.google-analytics.com/0.0.0.0:443
DEBUG (LoggingManagedHttpClientConnection.java:87) - http-outgoing-0: Shutdown connection
DEBUG (ConnectionHolder.java:126) - Connection discarded
DEBUG (LoggingManagedHttpClientConnection.java:79) - http-outgoing-0: Close connection
DEBUG (PoolingHttpClientConnectionManager.java:282) - Connection released: [id: 0][route: {s}->https://ssl.google-analytics.com:443][total kept alive: 0; route allocated: 0 of 1; total allocated: 0 of 20]
 WARN (GoogleAnalytics.java:167) - Exception while sending the Google Analytics tracker request Request [parms={HIT_TYPE=pageview, USER_LANGUAGE=en-US, PROTOCOL_VERSION=1, CLIENT_ID=d543bf19-f0e3-43f7-9be5-6ef8623793a8, DOCUMENT_URL=http://www.laccore.org, TRACKING_ID=UA-64269312-1, DOCUMENT_ENCODING=Cp1252, DOCUMENT_TITLE=launch: UUID=2a165524-60f1-4c86-aa16-ff5e487c0a91}, customDimensions={}, customMetrics={}]
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
... many many more lines later ....
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)



```

**Comment by knbknb** [comment]
What I'm blocking

`grep analytics /etc/hosts | grep goog`

```
0.0.0.0 analytics-api-samples.googlecode.com
0.0.0.0 google-analytics.com
0.0.0.0 ssl.google-analytics.com
0.0.0.0 www.google-analytics.com  #[affects Google Trends]
0.0.0.0 analytics.google.com
0.0.0.0 googleanalytics.com
0.0.0.0 www-google-analytics.l.google.com
# [google-analytics.com]
0.0.0.0 ssl-google-analytics.l.google.com

```

**Comment by sorghumking** [comment]
Launch tracking will be removed in the next release (TBD) of PSICAT.
